### PR TITLE
Communication protocol update, route information and protocol fixes

### LINKED ISSUE #31: Route information protocol

### PR DESCRIPTION
**Pull request by caspernorrbin**
Update to the protocol which introduces route information and fixes inconsistencies from the protocol and implementation.

- `get-route-info` and `route-info` implemented to give route vehicles take
- `id` and `line` fields are now strings, to better match with how they are stored and make it easier to send. (this is only a change to the protocol, as they were already stored as strings)

### CODE REVIEW

File: server/src/protocol/server_protocol.rs [hunk 1]
```diff
@@ -34,21 +34,39 @@ pub struct Vehicle {
...
 
-/// Represent a list of vehicles.
+/// Represent a line.
 #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
 #[serde(rename_all = "camelCase")]
 pub struct Line {
     pub timestamp: String,
     pub line: String,
-    pub vehicles: i32,
+    pub vehicles: u32,
```
Comment (joelsiks) [inline server/src/protocol/server_protocol.rs:44]: We'll see if it is relevant to keep track of the number of buses later on, but we can come back to this later when we've implemented this.

**Review by joelsiks — APPROVED** [review]

**Review by bjornmosten — APPROVED** [review]
